### ISSUE TITLE
トークページを作る

### ISSUE THREAD

**Issue by HiroshiIgarash** [saga-web-engineer/relumo#19]
トークページ：スレッドをクリックした時に出る画面。メッセージ投稿ができる

メッセージ入力欄、送信ボタン、メッセージ一覧があればいい

メッセージ一覧のレイアウトについて思いつくのは以下の通り
- LINE (吹き出し、自分のメッセージは右、ほかの人のメッセージは左)
- X(アイコンとメッセージ)

**Comment by saga-web-engineer** [comment]
同等の機能があるのでクローズ
