### ISSUE TITLE
通知が届くようにする

### ISSUE THREAD

**Issue by HiroshiIgarash** [saga-web-engineer/relumo#22]
メンションがあったら通知が届くようにする

通知機能は外部サービス使うことになると思う。コレミナへの実装は諦めた

メールでもいいかもしれない。そもそもネイティブアプリじゃないと通知はできなかったりする？わかんない

**Comment by saga-web-engineer** [comment]
掲示板アプリに通知はいらなさそうなのでこれもクローズ。
リリース後に通知ほしいとかあれば考える
