### ISSUE TITLE
actionの返り値の考察

### ISSUE THREAD

**Issue by HiroshiIgarash** [saga-web-engineer/relumo#27]
たとえば招待コード確認のactionでは文字列errorを返したら。。。。と言う分岐をしている

これだとエラーの内容によって変えるみたいなのができない。

```
{
    status: error,
    message: hogehogehogehoge
}
```

みたいなのとかあるけど、考える余地あり

**Comment by HiroshiIgarash** [comment]
https://monotein.com/blog/nextjs-server-actions-how-to-get-responses#hooksを使ったエラーハンドリング

server actions内でエラーがあった場合にのみエラーメッセージをreturnするやり方もある
これだと割とシンプルでよさげ
いまは"error"と言う文字列を返してるから、いまよりはマシになりそう

**Comment by saga-web-engineer** [comment]
conformを入れて解決
