### ISSUE TITLE
アイコン画像編集機能を作る？

### ISSUE THREAD

**Issue by HiroshiIgarash** [saga-web-engineer/relumo#30]
スマホ前提だとコレミナで使ったやつは微妙かも(クリッピング操作が直感的じゃない)

画像をどこに格納するかとか、割と考えること多い

いっそアイコン無くすのもあり(まかせる)

**Comment by saga-web-engineer** [comment]
アイコンは投稿画面には一切出さないので画像編集機能は今のところ実装する予定なし。
ユーザーからそういう声が上がりもしアイコンを出すことになったら再度考えるので一旦クローズ。
