### ISSUE TITLE
投稿モーダルをクローズした際に画面の一番下までスクロールする

### ISSUE THREAD

**Issue by saga-web-engineer** [saga-web-engineer/relumo#55]
タイトル通り、モーダルをクローズすると一番下までスクロールしてしまう。なんか前にposition: fixedで背景固定すると画面の一番上に戻るみたいなのを見かけた気がするけどそれに類似しているかも？モーダル出たときにbodyタグに色々とCSS付与されるから確認していったけど原因はわからなかった。shadcn/uiやradixのドキュメントとか見たけどわからない。
使ってて気持ち悪いから早めに修正したい。

**Comment by HiroshiIgarash** [comment]
issue見つけたけどまだ中見てないです
https://github.com/radix-ui/primitives/issues/3059

**Comment by HiroshiIgarash** [comment]
issue短いので翻訳とかして読んでみて欲しいのですが、どうやらとじた時にFocusがダイアログトリガーボタンに自動で移動するせいでおこるっぽいです
実際、TABを投稿ページで押していくとページネーション末尾の次にダイアログトリガーボタンがあり、ページネーション末尾（トリガーの１個前）にフォーカスを当ててページ上部までスクロールしてTABをおす（トリガーにフォーカスを移動する）と、モーダルとじた時と同様一番下まで移動するのでフォーカスが原因である可能性は高そうです
onCloseAutoFocusで解決したって書いてあるので試す価値ありかも。

**Comment by saga-web-engineer** [comment]
まじ助かったぜ
