### ISSUE TITLE
本番環境で投稿時にエラーになる

### ISSUE THREAD

**Issue by saga-web-engineer** [saga-web-engineer/relumo#87]

**Comment by HiroshiIgarash** [comment]
https://github.com/vercel/ai-chatbot/issues/291#issuecomment-2386532815

全部は読んでないけどこれで解決できる可能性あるかも

**Comment by HiroshiIgarash** [comment]
hobbyプランだとデフォルトで10秒になっているらしい
エラーが大体10秒くらいだったから解決できる可能性高そう

**Comment by saga-web-engineer** [comment]
解決はできるけど所要時間で課金されていく仕組みだからちょっと様子見しようかな？
https://vercel.com/docs/functions/configuring-functions/duration#consequences-of-changing-the-maximum-duration
